import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class Test3 here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Test3 extends Planet
{

    /**
     * Constructor for objects of class Test3.
     * 
     */
    public Test3()
    {
        Huegel huegel = new Huegel();
        addObject(huegel,6,3);
        Huegel huegel2 = new Huegel();
        addObject(huegel2,6,2);
        Huegel huegel3 = new Huegel();
        addObject(huegel3,7,2);
        Huegel huegel4 = new Huegel();
        addObject(huegel4,8,2);
        Huegel huegel5 = new Huegel();
        addObject(huegel5,9,2);
        huegel5.setLocation(9,2);
        Huegel huegel6 = new Huegel();
        addObject(huegel6,9,2);
        Huegel huegel7 = new Huegel();
        addObject(huegel7,10,2);
        Huegel huegel8 = new Huegel();
        addObject(huegel8,10,3);
        Huegel huegel9 = new Huegel();
        addObject(huegel9,10,4);
        Huegel huegel10 = new Huegel();
        addObject(huegel10,10,6);
        huegel9.setLocation(10,4);
        Huegel huegel11 = new Huegel();
        addObject(huegel11,10,4);
        huegel10.setLocation(10,6);
        Huegel huegel12 = new Huegel();
        addObject(huegel12,10,6);
        Huegel huegel13 = new Huegel();
        addObject(huegel13,8,6);
        Huegel huegel14 = new Huegel();
        addObject(huegel14,7,6);
        Huegel huegel15 = new Huegel();
        addObject(huegel15,6,6);
        Huegel huegel16 = new Huegel();
        addObject(huegel16,9,6);
        Huegel huegel17 = new Huegel();
        addObject(huegel17,10,5);
        Huegel huegel18 = new Huegel();
        addObject(huegel18,4,0);
        Huegel huegel19 = new Huegel();
        addObject(huegel19,4,1);
        huegel19.setLocation(4,1);
        Huegel huegel20 = new Huegel();
        addObject(huegel20,4,1);
        Huegel huegel21 = new Huegel();
        addObject(huegel21,4,2);
        Huegel huegel22 = new Huegel();
        addObject(huegel22,4,3);
        Huegel huegel23 = new Huegel();
        addObject(huegel23,4,4);
        huegel23.setLocation(4,4);
        Huegel huegel24 = new Huegel();
        addObject(huegel24,4,4);
        Huegel huegel25 = new Huegel();
        addObject(huegel25,4,6);
        Huegel huegel26 = new Huegel();
        addObject(huegel26,4,5);
        Huegel huegel27 = new Huegel();
        addObject(huegel27,4,8);
        Huegel huegel28 = new Huegel();
        addObject(huegel28,4,7);
        Huegel huegel29 = new Huegel();
        addObject(huegel29,5,8);
        Huegel huegel30 = new Huegel();
        addObject(huegel30,6,8);
        Huegel huegel31 = new Huegel();
        addObject(huegel31,7,8);
        Huegel huegel32 = new Huegel();
        addObject(huegel32,8,8);
        Huegel huegel33 = new Huegel();
        addObject(huegel33,9,8);
        Huegel huegel34 = new Huegel();
        addObject(huegel34,12,8);
        Huegel huegel35 = new Huegel();
        addObject(huegel35,10,8);
        Huegel huegel36 = new Huegel();
        addObject(huegel36,11,8);
        Huegel huegel37 = new Huegel();
        addObject(huegel37,12,7);
        Huegel huegel38 = new Huegel();
        addObject(huegel38,12,6);
        Huegel huegel39 = new Huegel();
        addObject(huegel39,12,5);
        Huegel huegel40 = new Huegel();
        addObject(huegel40,14,5);
        Huegel huegel41 = new Huegel();
        addObject(huegel41,14,6);
        Huegel huegel42 = new Huegel();
        addObject(huegel42,14,7);
        Huegel huegel43 = new Huegel();
        addObject(huegel43,14,8);
        Huegel huegel44 = new Huegel();
        addObject(huegel44,14,10);
        huegel44.setLocation(14,10);
        Huegel huegel45 = new Huegel();
        addObject(huegel45,14,10);
        Huegel huegel46 = new Huegel();
        addObject(huegel46,15,10);
        Huegel huegel47 = new Huegel();
        addObject(huegel47,14,9);
        Huegel huegel48 = new Huegel();
        addObject(huegel48,12,0);
        huegel48.setLocation(12,0);
        Huegel huegel49 = new Huegel();
        addObject(huegel49,12,0);
        Huegel huegel50 = new Huegel();
        addObject(huegel50,12,1);
        Huegel huegel51 = new Huegel();
        addObject(huegel51,13,1);
        huegel51.setLocation(13,1);
        Huegel huegel52 = new Huegel();
        addObject(huegel52,13,1);
        Huegel huegel53 = new Huegel();
        addObject(huegel53,13,2);
        Huegel huegel54 = new Huegel();
        addObject(huegel54,14,2);
        huegel54.setLocation(14,2);
        Huegel huegel55 = new Huegel();
        addObject(huegel55,15,2);
        Huegel huegel56 = new Huegel();
        addObject(huegel56,15,3);
        Huegel huegel57 = new Huegel();
        addObject(huegel57,2,1);
        Huegel huegel58 = new Huegel();
        addObject(huegel58,2,2);
        Huegel huegel59 = new Huegel();
        addObject(huegel59,2,3);
        Huegel huegel60 = new Huegel();
        addObject(huegel60,1,3);
        Huegel huegel61 = new Huegel();
        addObject(huegel61,1,4);
        huegel61.setLocation(1,4);
        Huegel huegel62 = new Huegel();
        addObject(huegel62,1,4);
        Huegel huegel63 = new Huegel();
        addObject(huegel63,1,5);
        huegel63.setLocation(1,5);
        Huegel huegel64 = new Huegel();
        addObject(huegel64,1,5);
        Huegel huegel65 = new Huegel();
        addObject(huegel65,2,6);
        huegel65.setLocation(2,6);
        Huegel huegel66 = new Huegel();
        addObject(huegel66,2,6);
        Huegel huegel67 = new Huegel();
        addObject(huegel67,3,6);
        Huegel huegel68 = new Huegel();
        addObject(huegel68,3,5);
        Huegel huegel69 = new Huegel();
        addObject(huegel69,1,6);
        Huegel huegel70 = new Huegel();
        addObject(huegel70,0,1);
        Huegel huegel71 = new Huegel();
        addObject(huegel71,0,8);
        Huegel huegel72 = new Huegel();
        addObject(huegel72,1,8);
        Huegel huegel73 = new Huegel();
        addObject(huegel73,1,9);
        Huegel huegel74 = new Huegel();
        addObject(huegel74,2,9);
        Huegel huegel75 = new Huegel();
        addObject(huegel75,4,9);
        removeObject(huegel74);
        removeObject(huegel73);
        huegel74.setLocation(3,10);
        Huegel huegel76 = new Huegel();
        addObject(huegel76,3,10);
        Huegel huegel77 = new Huegel();
        addObject(huegel77,2,10);
        huegel77.setLocation(2,10);
        Huegel huegel78 = new Huegel();
        addObject(huegel78,2,10);
        Huegel huegel79 = new Huegel();
        addObject(huegel79,2,8);
        Huegel huegel80 = new Huegel();
        addObject(huegel80,1,10);
        Huegel huegel81 = new Huegel();
        addObject(huegel81,6,11);
        Huegel huegel82 = new Huegel();
        addObject(huegel82,6,10);
        Huegel huegel83 = new Huegel();
        addObject(huegel83,8,9);
        Huegel huegel84 = new Huegel();
        addObject(huegel84,8,10);
        Huegel huegel85 = new Huegel();
        addObject(huegel85,9,10);
        Huegel huegel86 = new Huegel();
        addObject(huegel86,10,10);
        Huegel huegel87 = new Huegel();
        addObject(huegel87,12,11);
        Huegel huegel88 = new Huegel();
        addObject(huegel88,12,10);
        Marke marke = new Marke();
        addObject(marke,8,4);
        Rover rover = new Rover();
        addObject(rover,2,5);
        marke.showChords();
        marke.showChords();
        rover.toPoint(8, 4);
        rover.toPoint(0, 0);
        rover.toPoint(7, 1);
        huegel34.setLocation(12,8);
    }
}
